"""Append deterministic, distinct fixed boards; never renumber existing puzzles."""
import importlib.util,json,pathlib,random,copy
ROOT=pathlib.Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('builders',ROOT/'scripts/build-puzzles.py');b=importlib.util.module_from_spec(spec);spec.loader.exec_module(b)
def load(name):return json.loads((ROOT/f'data/puzzles/{name}.js').read_text().split('export default ',1)[1].strip().removesuffix(';'))
def signature(d):
 return json.dumps({k:d[k] for k in ['givens','cages','rules','blocked','target'] if k in d},sort_keys=True)
def harder_sudoku(rng):
 d=b.sudoku(rng);givens=d['givens']
 for index in rng.sample(range(81),81):
  old=givens[index];givens[index]=0
  if len(b.sudoku_solve(givens))!=1:givens[index]=old
 complete,tech,steps,trace=b.human_singles(givens)
 d['validation']={'solutionCount':1,'method':'backtracking uniqueness','techniques':tech,'deductionSteps':steps,'deductionTrace':trace,'singlesComplete':complete}
 return d
# Larger cages use the same independent Latin-square solver, with fewer singleton clues.
source=(ROOT/'scripts/build-puzzles.py').read_text();start=source.index('def cages(rng):');end=source.index("\nif __name__",start)
ns=dict(vars(b));exec(source[start:end].replace('def cages(rng):','def harder_cages(rng):').replace('n=5','n=6').replace("[1,1,2]","[1,2,2,3]").replace('1–5','1–6'),ns)
families=[('logic-grids','logic grids','logic-grid',lambda r,l:b.logic(r,2 if l=='foundation' else 3)),('logic-equations','logic equations','equation-grid',lambda r,l:b.equations(r,5 if l=='foundation' else 7 if l=='standard' else 8)),('sudoku','sudoku','sudoku',lambda r,l:harder_sudoku(r) if l=='stretch' else b.sudoku(r)),('cover-paths','cover paths','cover-path',lambda r,l:b.cover_path(r,5 if l=='foundation' else 6 if l=='standard' else 7)),('tangrams','tangrams','tiling',lambda r,l:b.tangram(r)),('number-constraints','number constraints','cage-grid',lambda r,l:ns['harder_cages'](r) if l=='stretch' else b.cages(r))]
for family,(filename,focus,kind,make) in enumerate(families):
 bank=load(filename)[:5];seen={signature(v['parts'][0]) for q in bank for v in q['variations']}
 for j in range(45):
  level=['foundation','standard','stretch'][j//15];rng=random.Random(93000+family*10000+j*113)
  for attempt in range(200):
   try:d=make(rng,level)
   except AssertionError:continue
   sig=signature(d)
   if sig not in seen:break
  else:raise ValueError('Could not generate distinct puzzle')
  seen.add(sig)
  slot=300+family*45+j
  v={'prompt':d.pop('prompt'),'hint':bank[0]['variations'][0]['hint'],'parts':[{'id':'0','prompt':'Solve the puzzle.','kind':kind,'marks':3,'answer':json.dumps(d.pop('solution')),'explanation':d.pop('explanation'),'solutionText':d.pop('solutionText','See the completed board below.'),**d}]}
  # Existing tangrams are already compact; label by outline complexity provisionally, not generation order.
  if kind=='tiling':
   points=set(tuple(p) for poly in d['target'] for p in poly);area=(max(x for x,y in points)-min(x for x,y in points))*(max(y for x,y in points)-min(y for x,y in points))
   level='stretch' if area<=12 else 'standard' if area<=16 else 'foundation'
  bank.append({'slot':slot,'focus':focus,'title':f'{focus.title()} {j+6}','format':'Reasoning puzzle','tags':[f'challenge:{level}'],'challengeLevel':level,'fixed':True,'setSize':3,'estimatedMinutes':10,'variations':[v]})
  if j%15==14:print(filename,j+6,flush=True)
 (ROOT/f'data/puzzles/{filename}.js').write_text('// Original variations retained; additions generated by scripts/expand-puzzles.py.\nexport default '+json.dumps(bank,ensure_ascii=False,separators=(',',':'))+';\n')

# Make foundation boards simpler and remove symmetry-equivalent silhouettes.
import runpy
runpy.run_path(str(ROOT/"scripts/refine-puzzles.py"))
